# Generated by Django 5.2.7 on 2026-01-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='default.png'),
        ),
    ]
