import type { Metadata } from "next";
import { Lato} from "next/font/google";
import "./globals.css";



const latofont = Lato({
  weight: ['100', '300', '400', '700', '900'], // Specify weights you need
  subsets: ['latin'],
  variable: '--font-lato', // CSS variable name
  display: 'swap', // Optional: improves loading performance
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white max-w-7xl mx-auto">
      <body
        className={`${latofont.variable} antialiased`}
      >
        
      
      
       
        {children}
      </body>
    </html>
  );
}
